### ISSUE TITLE
Level 1 with non Domain Joined Devices

### ISSUE THREAD

**Issue by muradmomani** [microsoft/SecCon-Framework#11]
Hi,

I have around 15 **windows 10** machine and they are **nondomain joined**, they are used for the daily working process and accessing cloud data, mainly the used programs are web browsers and office applications with some default windows applications.

I went over the Level 1 security recommendation pointed here: _https://github.com/microsoft/SecCon-Framework/blob/master/level-1-enterprise-basic-security.md_  and thinking to **skip** the security recommendations that have the Domain member as my devices are not domain-joined.

is that a correct approach to implement the previously mentioned recommendation ! to skip Domain member controles on the non-domain devices?  

Thanks in advance.

**Comment by appcompatguy** [comment]
Yes - if a configuration is not relevant, you can feel free to just leave it out of what you apply. Out of curiosity, how are you applying policies?

**Comment by alexverboon** [comment]
It would be great if we could include guidance and recommendations to the security baselines for non-domain joined i.e. modern workplaces. We have noticed that when configuring devices with Intune, not all the configuration settings referenced in the security configuration baselines are available natively in the UI, some can be configured using OMA URI settings or by using scripting, but the question really is, do we actually need to configure settings on a modern workplace that are usually only needed for domain joined devices. A good example is audit logging, unless I deploy some sort of cloud based log collector solution such as the MMA agent on my windows client devices, or IT security would still wish to have local security logs enabled, I feel that there is no requirement to add such configuration to a AzureAD registered device. What are your thoughts on this?
