### ISSUE TITLE
Deploy Windows Quality Updates within 4 days

### ISSUE THREAD

**Issue by alexverboon** [microsoft/SecCon-Framework#6]
Hello, 
My input here would be to state that the deployment should be prepared and started within 4 days, and completed within the shortest possible time frame, however i doubt any 'enterprise' does this within 4 days. 
When looking at most mid to large size enterprises they usually follow a process where updates are deployed in stages, such as Test, Pilot and the into production. What i usually recommend and also see happening is
1. Patch/Update is released, start immediate deployment to test ring (2-3 days)
2. Deploy to pilot ring (2-4 days)
3. Deploy into production (3-5 days)

This comes close to patching is completed 2.5 weeks after its release. 
Any thoughts?

**Comment by gavsto** [comment]
Completely agree. I think you'd have to hold a gun to most System Administrator's head to get them yo deploy Quality Updates in a 4 day window.

**Comment by appcompatguy** [comment]
That's really good feedback. There's a lot of debate in this space - while some orgs want to get the number of weeks down lower, there are others who want to start measuring patch deployment in hours, not days or weeks. As with many things, I think matching the right scenario to the right timeframe is important - I wouldn't think of 2.5 weeks as the overall answer would be good enough in today's threat environment.

We're working right now with the NIST National Cybersecurity Center of Excellence to establish some more actionable and nuanced guidance, and will look to update based on the outcome of that industry-wide investigation.
