### ISSUE TITLE
Gap Analysis

### ISSUE THREAD

**Issue by port9org** [microsoft/SecCon-Framework#8]
is there a simple way to map the requirements of a **Level 1 Enterprise Basic Security configuration** against an existing domain joined w10-endpoint? 

I found the security baselines within the Security Compliance Toolkit but they don't seem to be the same as the Level 1-5 configurations?

**Comment by appcompatguy** [comment]
Hi @port9org - the initial release is documentation only, and we have been using it together feedback and ensure that the settings meet the stated goals. We are working on implementing them to make them easier to apply. Today, the SCT will allow you to apply SecCon 3 to a device (we align here to the full baseline, for policies), but it remains a manual effort to modify to a lower SecCon level. We do hope to continue making this easier as we have seen a lot of demand for it!
